# Numpy
## Numpy >> Numerical Python

### Definition:
NumPy is a powerful Python library used for numerical computing. It provides support for large multidimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

### Applications:
1. **Linear Algebra**: Perform matrix operations like dot product, matrix multiplication, and inversion.
2. **Statistics**: Calculate statistical metrics like mean, mode, median, standard deviation, and variance.
3. **Probability**: Simulate random experiments and probability distributions.
4. **Image Processing**: Manipulate pixel data for image transformations and analysis.
5. **Trigonometry**: Work with trigonometric functions such as sin, cos, tan, etc.
6. **Random Number Generation**: Generate random samples from different distributions.
7. **Logarithmic Functions**: Perform logarithmic and exponential operations efficiently.

### Key Features:
- **Homogeneous Data Types**: All elements in a NumPy array must be of the same data type.
- **ndarray**: NumPy's n-dimensional array object supports 0D (scalars), 1D (vectors), 2D (matrices), and nD arrays.
- **Speed**: NumPy arrays are faster and more memory-efficient than Python lists due to their implementation in C and C++.
- **Flexibility**: Arrays can be created from Python lists or tuples and offer powerful tools for reshaping, slicing, and broadcasting.



# Understanding NumPy: A Comprehensive Guide

NumPy (Numerical Python) is a fundamental library for numerical computations in Python.

---

## 1. Creating Arrays

- `np.array()`  
  Creates an array from lists or tuples.

- `np.zeros()`  
  Creates an array filled with zeros.

- `np.ones()`  
  Creates an array filled with ones.

- `np.empty()`  
  Creates an empty array with uninitialized values.

- `np.full()`  
  Creates an array filled with a specified value.

- `np.arange()`  
  Creates an array with evenly spaced values within a range.

- `np.linspace()`  
  Creates an array with evenly spaced numbers over a specified interval.

- `np.eye()`  
  Creates an identity matrix.

- `np.random.rand()`  
  Generates an array of random values from a uniform distribution.

- `np.random.randn()`  
  Generates an array of random values from a standard normal distribution.

- `np.random.randint()`  
  Generates an array of random integers within a range.

- `np.random.choice()`  
  Randomly selects elements from an array.

- `np.fromfunction()`  
  Constructs an array using a function.

---

## 2. Array Attributes and Properties

- `array.shape`  
  Returns the shape of the array.

- `array.size`  
  Returns the total number of elements in the array.

- `array.ndim`  
  Returns the number of dimensions (axes) of the array.

- `array.dtype`  
  Returns the data type of array elements.

- `array.itemsize`  
  Returns the size in bytes of each element in the array.

- `array.nbytes`  
  Returns the total memory consumed by the array in bytes.

- `array.T`  
  Returns the transposed array.

- `np.amin()`  
  Returns the minimum value of the array.

- `np.amax()`  
  Returns the maximum value of the array.

- `np.ptp()`  
  Returns the range (max - min) of the array.

---

## 3. Indexing and Slicing

- `array[index]`  
  Accesses an element at the specified index.

- `array[start:stop]`  
  Slices an array from start to stop (exclusive).

- `array[start:stop:step]`  
  Slices an array with a specific step size.

- `array[..., index]`  
  Accesses elements in multi-dimensional arrays.

- `array[:, 1]`  
  Accesses a specific column in a 2D array.

- `np.where()`  
  Returns the indices of elements that satisfy a condition.

- `np.take()`  
  Extracts elements along a specified axis.

- `np.put()`  
  Replaces specified elements in an array.

---

## 4. Reshaping and Modifying Arrays

- `np.reshape()`  
  Changes the shape of an array without altering its data.

- `array.flatten()`  
  Flattens a multi-dimensional array into a 1D array.

- `array.ravel()`  
  Returns a flattened array view (no data copy).

- `np.expand_dims()`  
  Expands the shape of an array by adding a new axis.

- `np.squeeze()`  
  Removes axes of size 1 from the shape of an array.

- `np.concatenate()`  
  Joins arrays along an existing axis.

- `np.stack()`  
  Stacks arrays along a new axis.

- `np.hstack()`  
  Stacks arrays horizontally.

- `np.vstack()`  
  Stacks arrays vertically.

- `np.split()`  
  Splits an array into multiple sub-arrays.

---

## 5. Mathematical Operations

- `np.add()`  
  Element-wise addition.

- `np.subtract()`  
  Element-wise subtraction.

- `np.multiply()`  
  Element-wise multiplication.

- `np.divide()`  
  Element-wise division.

- `np.power()`  
  Raises elements to a power.

- `np.sqrt()`  
  Computes the square root of each element.

- `np.log()`  
  Computes the natural logarithm of each element.

- `np.exp()`  
  Computes the exponential of each element.

- `np.sum()`  
  Computes the sum of elements along an axis.

- `np.prod()`  
  Computes the product of elements along an axis.

- `np.mean()`  
  Computes the mean of elements along an axis.

- `np.std()`  
  Computes the standard deviation.

- `np.var()`  
  Computes the variance.

- `np.cumsum()`  
  Computes the cumulative sum of elements.

- `np.cumprod()`  
  Computes the cumulative product of elements.

---

## 6. Logical Operations

- `np.all()`  
  Tests whether all elements evaluate to `True`.

- `np.any()`  
  Tests whether any element evaluates to `True`.

- `np.logical_and()`  
  Computes element-wise logical AND.

- `np.logical_or()`  
  Computes element-wise logical OR.

- `np.logical_not()`  
  Computes element-wise logical NOT.

- `np.logical_xor()`  
  Computes element-wise logical XOR.

- `np.isclose()`  
  Tests whether two arrays are element-wise equal within a tolerance.

- `np.array_equal()`  
  Checks if two arrays are element-wise equal.

---

## 7. Linear Algebra Operations

- `np.dot()`  
  Computes the dot product of two arrays.

- `np.matmul()`  
  Performs matrix multiplication.

- `np.linalg.inv()`  
  Computes the inverse of a square matrix.

- `np.linalg.det()`  
  Computes the determinant of a square matrix.

- `np.linalg.eig()`  
  Computes the eigenvalues and eigenvectors.

- `np.linalg.svd()`  
  Performs singular value decomposition (SVD).

- `np.linalg.norm()`  
  Computes the norm of a vector or matrix.

- `np.linalg.solve()`  
  Solves a linear matrix equation.

- `np.trace()`  
  Computes the sum of diagonal elements of a matrix.

---

## 8. Broadcasting and Vectorization

- `array + scalar`  
  Adds a scalar to each element (broadcasting).

- `array * scalar`  
  Multiplies each element by a scalar.

- `np.vectorize()`  
  Applies a function element-wise on arrays.

---

## 9. Sorting and Searching

- `np.sort()`  
  Sorts an array along a specified axis.

- `np.argsort()`  
  Returns the indices of sorted elements.

- `np.argmin()`  
  Returns the index of the minimum value.

- `np.argmax()`  
  Returns the index of the maximum value.

- `np.searchsorted()`  
  Finds indices where elements should be inserted to maintain order.

---

## 10. Random Functions

- `np.random.seed()`  
  Sets the seed for reproducibility.

- `np.random.rand()`  
  Generates random values from a uniform distribution.

- `np.random.randn()`  
  Generates random values from a normal distribution.

- `np.random.randint()`  
  Generates random integers within a specified range.

- `np.random.permutation()`  
  Randomly permutes a sequence.

- `np.random.shuffle()`  
  Shuffles an array in place.

---

## 11. File I/O Operations

- `np.save()`  
  Saves an array to a binary file.

- `np.load()`  
  Loads an array from a binary file.

- `np.savetxt()`  
  Saves an array to a text file.

- `np.loadtxt()`  
  Loads data from a text file into an array.

- `np.genfromtxt()`  
  Loads data from a text file, with missing values handled.

- `np.fromfile()`  
  Reads data from a binary file into an array.


In [2]:
import numpy as np

# 1. Creating Arrays

In [3]:
arr1 = np.array([1, 2, 3])                    # Create array from list
arr1

array([1, 2, 3])

In [4]:
zeros = np.zeros((2, 3))                      # Array of zeros
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
ones = np.ones((3, 3))                        # Array of ones
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
empty = np.empty((2, 2))                      # Empty array
empty

array([[5.03244676e-310, 0.00000000e+000],
       [5.03303860e-310, 6.71108834e-310]])

In [7]:
full = np.full((2, 2), 7)                     # Array filled with 7
full

array([[7, 7],
       [7, 7]])

In [8]:
arange = np.arange(0, 10, 2)                  # Evenly spaced values
arange

array([0, 2, 4, 6, 8])

In [9]:
linspace = np.linspace(0, 1, 5)               # Evenly spaced numbers
linspace

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
identity = np.eye(3)                          # Identity matrix
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
rand_uniform = np.random.rand(2, 3)           # Random uniform distribution
rand_uniform

array([[0.05376876, 0.65596057, 0.942851  ],
       [0.42914073, 0.93055255, 0.73759403]])

In [12]:
rand_normal = np.random.randn(2, 3)           # Random normal distribution
rand_normal

array([[ 1.24395188,  0.60815691, -0.24052462],
       [-1.00328485, -0.64750265,  0.40483414]])

In [13]:
rand_int = np.random.randint(0, 10, size=5)   # Random integers
rand_int

array([7, 0, 9, 8, 8])

In [14]:
rand_choice = np.random.choice([1, 2, 3])     # Random choice from list
rand_choice

2

In [15]:
from_func = np.fromfunction(lambda i, j: i + j, (3, 3))  # From function
from_func

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

# 2. Array Attributes

In [16]:
shape = arr1.shape                            # Shape of array
shape

(3,)

In [17]:
size = arr1.size                              # Total elements
size

3

In [18]:
ndim = arr1.ndim                              # Number of dimensions
ndim

1

In [19]:
dtype = arr1.dtype                            # Data type
dtype

dtype('int64')

In [20]:
itemsize = arr1.itemsize                      # Size of one element in bytes
itemsize

8

In [21]:
nbytes = arr1.nbytes                          # Total memory in bytes
nbytes

24

In [22]:
transpose = arr1.T                            # Transpose
transpose

array([1, 2, 3])

In [23]:
amin = np.amin(arr1)                          # Minimum value
amin

1

In [24]:
amax = np.amax(arr1)                          # Maximum value
amax

3

In [25]:
range_ptp = np.ptp(arr1)                      # Range (max - min)
range_ptp

2

# 3. Indexing and Slicing

In [26]:
element = arr1[0]                             # Access element
element

1

In [27]:
slice_array = arr1[0:2]                       # Slice array
slice_array

array([1, 2])

In [28]:
step_slice = arr1[0:3:2]                      # Slice with step
step_slice

array([1, 3])

In [29]:
multi_dim = np.array([[1, 2], [3, 4]])
multi_dim

array([[1, 2],
       [3, 4]])

In [30]:
col = multi_dim[:, 1]                         # Access column
col

array([2, 4])

In [31]:
condition = np.where(arr1 > 1)                # Where condition
condition

(array([1, 2]),)

In [32]:
take = np.take(arr1, [0, 2])                  # Take elements
take

array([1, 3])

In [33]:
put = np.put(arr1, [0], [-1])                 # Modify elements
put

# 4. Reshaping

In [34]:
reshaped = np.reshape(arr1, (1, 3))           # Reshape array
reshaped

array([[-1,  2,  3]])

In [35]:
flattened = arr1.flatten()                    # Flatten array
flattened

array([-1,  2,  3])

In [36]:
ravelled = arr1.ravel()                       # Ravel array
ravelled

array([-1,  2,  3])

In [37]:
expanded = np.expand_dims(arr1, axis=0)       # Expand dims
expanded

array([[-1,  2,  3]])

In [38]:
squeezed = np.squeeze(expanded)               # Squeeze array
squeezed

array([-1,  2,  3])

In [39]:
concat = np.concatenate((arr1, arr1))         # Concatenate
concat

array([-1,  2,  3, -1,  2,  3])

In [40]:
stacked = np.stack([arr1, arr1])              # Stack arrays
stacked

array([[-1,  2,  3],
       [-1,  2,  3]])

In [41]:
hstack = np.hstack([arr1, arr1])              # Horizontal stack
hstack

array([-1,  2,  3, -1,  2,  3])

In [42]:
vstack = np.vstack([arr1, arr1])              # Vertical stack
vstack


array([[-1,  2,  3],
       [-1,  2,  3]])

In [43]:
splitted = np.split(arr1, 3)                  # Split array
splitted

[array([-1]), array([2]), array([3])]

# 5. Mathematical Operations

In [44]:
added = np.add(arr1, arr1)                    # Element-wise addition
added

array([-2,  4,  6])

In [45]:
subtracted = np.subtract(arr1, arr1)          # Element-wise subtraction
subtracted

array([0, 0, 0])

In [46]:
multiplied = np.multiply(arr1, arr1)          # Element-wise multiplication
multiplied

array([1, 4, 9])

In [47]:
divided = np.divide(arr1, arr1 + 1)           # Element-wise division
divided

<ipython-input-47-0e6886aef15a>:1: RuntimeWarning: divide by zero encountered in divide
  divided = np.divide(arr1, arr1 + 1)           # Element-wise division


array([      -inf, 0.66666667, 0.75      ])

In [48]:
powered = np.power(arr1, 2)                   # Power
powered

array([1, 4, 9])

In [49]:
sqrted = np.sqrt(arr1 + 1)                    # Square root
sqrted

array([0.        , 1.73205081, 2.        ])

In [50]:
logged = np.log(arr1 + 1)                     # Logarithm
logged

<ipython-input-50-f1b1a2b9eca4>:1: RuntimeWarning: divide by zero encountered in log
  logged = np.log(arr1 + 1)                     # Logarithm


array([      -inf, 1.09861229, 1.38629436])

In [51]:
exponential = np.exp(arr1)                    # Exponential
exponential

array([ 0.36787944,  7.3890561 , 20.08553692])

In [52]:
summed = np.sum(arr1)                         # Sum
summed

4

In [53]:
product = np.prod(arr1)                       # Product
product

-6

In [54]:
mean_val = np.mean(arr1)                      # Mean
mean_val

1.3333333333333333

In [55]:
std_dev = np.std(arr1)                        # Standard deviation
std_dev

1.699673171197595

In [56]:
variance = np.var(arr1)                       # Variance
variance

2.888888888888889

In [57]:
cumsum = np.cumsum(arr1)                      # Cumulative sum
cumsum

array([-1,  1,  4])

In [58]:
cumprod = np.cumprod(arr1)                    # Cumulative product
cumprod

array([-1, -2, -6])

# 6. Logical Operations

In [59]:
logical_and = np.logical_and(arr1 > 0, arr1 < 3)
logical_and

array([False,  True, False])

In [60]:
logical_or = np.logical_or(arr1 > 2, arr1 < 1)
logical_or

array([ True, False,  True])

In [61]:
logical_not = np.logical_not(arr1 > 2)
logical_not

array([ True,  True, False])

In [62]:
logical_xor = np.logical_xor(arr1 > 0, arr1 > 1)
logical_xor

array([False, False, False])

In [63]:
is_close = np.isclose(arr1, arr1)
is_close

array([ True,  True,  True])

In [64]:
array_equal = np.array_equal(arr1, arr1)
array_equal

True

In [ ]:
# 7. Linear Algebra
dot_product = np.dot(arr1, arr1)
matrix_mult = np.matmul(multi_dim, multi_dim.T)
matrix_inv = np.linalg.inv(np.eye(3))
det = np.linalg.det(np.eye(3))
eig_values, eig_vectors = np.linalg.eig(np.eye(3))
svd = np.linalg.svd(np.eye(3))
norm = np.linalg.norm(arr1)
solve = np.linalg.solve(np.eye(2), [1, 1])
trace = np.trace(np.eye(3))


# 7. Linear Algebra

In [65]:
dot_product = np.dot(arr1, arr1)
dot_product

14

In [66]:
matrix_mult = np.matmul(multi_dim, multi_dim.T)
matrix_mult

array([[ 5, 11],
       [11, 25]])

In [67]:
matrix_inv = np.linalg.inv(np.eye(3))
matrix_inv

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [68]:
det = np.linalg.det(np.eye(3))
det

1.0

In [69]:
eig_values, eig_vectors = np.linalg.eig(np.eye(3))
eig_values

array([1., 1., 1.])

In [70]:
eig_vectors

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [71]:
svd = np.linalg.svd(np.eye(3))
svd

SVDResult(U=array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]), S=array([1., 1., 1.]), Vh=array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]))

In [72]:
norm = np.linalg.norm(arr1)
norm

3.7416573867739413

In [73]:
solve = np.linalg.solve(np.eye(2), [1, 1])
solve

array([1., 1.])

In [74]:
trace = np.trace(np.eye(3))
trace

3.0

# 8. Broadcasting and Vectorization

In [75]:
broadcast_add = arr1 + 2                      # Broadcasting
broadcast_add

array([1, 4, 5])

In [76]:
vectorized = np.vectorize(lambda x: x ** 2)(arr1)  # Vectorize
vectorized

array([1, 4, 9])

# 9. Sorting and Searching

In [77]:
sorted_array = np.sort(arr1)
sorted_array

array([-1,  2,  3])

In [78]:
argsorted = np.argsort(arr1)
argsorted

array([0, 1, 2])

In [79]:
argmin = np.argmin(arr1)
argmin

0

In [80]:
argmax = np.argmax(arr1)
argmax

2

In [81]:
search_sorted = np.searchsorted(arr1, 1)
search_sorted

1

# 10. Random

In [82]:
np.random.seed(42)                            # Set seed

In [83]:
rand_uniform = np.random.rand(3)
rand_uniform

array([0.37454012, 0.95071431, 0.73199394])

In [84]:
rand_normal = np.random.randn(3)
rand_normal

array([-1.11188012,  0.31890218,  0.27904129])

In [85]:
rand_int = np.random.randint(0, 10, 3)
rand_int

array([7, 2, 5])

In [86]:
permutation = np.random.permutation(arr1)
permutation

array([ 3,  2, -1])

In [87]:
np.random.shuffle(arr1)


# 11. File I/O

In [88]:
np.save('array.npy', arr1)                    # Save binary

In [89]:
loaded_array = np.load('array.npy')           # Load binary
loaded_array

array([-1,  3,  2])

In [90]:
np.savetxt('array.txt', arr1)                 # Save text

In [91]:
loaded_text = np.loadtxt('array.txt')         # Load text
loaded_text

array([-1.,  3.,  2.])

In [92]:
gen_txt = np.genfromtxt('array.txt')          # Load with NaN handling
gen_txt

array([-1.,  3.,  2.])

In [93]:
from_file = np.fromfile('array.npy')          # Load from binary file
from_file

array([1.87585069e-309, 1.17119999e+171, 5.93271341e-037, 8.44740097e+252,
       2.65141232e+180, 9.92152605e+247, 2.16209968e+233, 2.34519039e-110,
       6.01347003e-154, 6.01347002e-154, 6.01347002e-154, 6.01347002e-154,
       6.01347002e-154, 6.01347002e-154, 6.01347002e-154, 6.55490914e-260,
                   nan, 1.48219694e-323, 9.88131292e-324])